name: Check PR Title

on:
  workflow_run:
    workflows: ["Validate Permissions"]
    types: 
      - completed
  pull_request:
    branches: [main, develop]
    types: [opened, synchronize, reopened, edited]

jobs:
  check-pr-title:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: juv-dev/workflows-frontend/.github/workflows/check-pr-title.yml@main
