name: Load Values

on:
  workflow_run:
    workflows: ["Validate Permissions"]
    types: 
      - completed
  pull_request:
    branches: [main, develop]
  push:
    branches: [main, develop]

jobs:
  load-values:
    if: ${{ github.event_name != 'workflow_run' || github.event.workflow_run.conclusion == 'success' }}
    uses: juv-dev/workflows-frontend/.github/workflows/load-env.yml@main
    with:
      environment: ${{ github.ref_name == 'main' && 'production' || 'development' }}
